### ISSUE TITLE
Support alphanumeric codes

### ISSUE THREAD

**Issue by jrtibbetts** [theedov/OneTimeCodeTextField#1]
This seems straightforward enough to do:

* Declare `OneTimeCodeTextFieldDelegate` public.
* Declare a property for the allowed `CharacterSet`.
* Declare `OneTimeCodeTextField.oneTimeCodeDelegate` public.

**Comment by jrtibbetts** [comment]
I created PR #2 to support this.

**Comment by theedov** [comment]
Thanks #2 merged 🎉
